### ISSUE TITLE
Zombie's Retreat Cheat Script V0.14.4 Not Working

### ISSUE THREAD

**Issue by zzzullian** [Jim00000/Zombies-Retreat-2-Cheat-Script#3]
Bro cheat script v0.14.4 not working

**Comment by Jim00000** [comment]
Thanks for reporting the bug.

It looks like javascript version in RPGMaker doesn't support class static property right now.

A fix patch gets ready and you can try it out. 

https://github.com/Jim00000/Zombies-Retreat-2-Cheat-Script/archive/refs/heads/issue-2.zip

Thanks.

**Comment by zzzullian** [comment]
oh thanks this file perfectly work
